spring.application.name=formation-spring-boot-project
management.endpoints.web.exposure.include=health,info,env,metrics,beans,loggers
management.endpoint.health.show-details=always
management.endpoints.jmx.exposure.exclude=*

app.name=Formation Spring Boot
app.version=1.0.0
app.environment=DEFAULT
app.debug=false
database.url=jdbc:h2:mem:testdb
database.username=sa
database.password=
logging.level.root=WARN

#spring.active.profiles=dev