app.environment=DEVELOPMENT
logging.level.root=DEBUG
logging.level.fr.insee.formation=DEBUG

spring.datasource.url=jdbc:h2:mem:devdb
spring.datasource.username=dev_user
spring.datasource.password=dev_password
spring.h2.console.enabled=true

management.endpoint.env.show-values=ALWAYS