app.environment=INTEGRATION

logging.level.root=WARN
logging.level.fr.insee.formation=INFO

spring.datasource.url=jdbc:h2:file:./data/integrationdb;MODE=MySQL
spring.datasource.username=user_integration
spring.datasource.password=pwd_integration
spring.h2.console.enabled=false