app.environment=INTEGRATION
app.debug=false
database.url=jdbc:h2:mem:integrationdb
database.username=integration_user
database.password=integration_secure_pass
logging.level.root=INFO
logging.level.fr.insee.formation=DEBUG