app.environment=DEVELOPMENT
logging.level.root=DEBUG
logging.level.fr.insee.formation=DEBUG

spring.datasource.url=jdbc:h2:mem:devdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true